name: Scheduled Repository Check

on:
  schedule:
    - cron: '* * * * *'  # 每1分鐘執行一次

jobs:
  check_repo_update:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Latest Commit SHA from Target Repository
        id: fetch_commit
        run: |
          latest_commit=$(curl -s -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/nkxrfxforum/Test/commits | jq -r '.[0].sha')
          echo "LATEST_COMMIT=$latest_commit" >> $GITHUB_ENV  # 將變數寫入 GITHUB_ENV

      - name: Compare Commits and Notify if New
        env:
          LATEST_COMMIT: ${{ env.LATEST_COMMIT }}  # 使用寫入的環境變數
        run: |
          # 假設上次的提交 SHA 也已保存或從外部源獲取
          if [ "$LATEST_COMMIT" != "$PREVIOUS_COMMIT" ]; then
            echo "New commit detected: $LATEST_COMMIT"
            echo "PREVIOUS_COMMIT=$LATEST_COMMIT" >> $GITHUB_ENV  # 更新 GITHUB_ENV
            # 暫時註解掉發送通知的命令
            # curl -X POST http://localhost:5000/notify -H "Content-Type: application/json" -d '{"message": "New update in nkxrfxforum/Test!"}'
          else
            echo "No new commits."
          fi
